index = "idx"
corpus = "line.toml"
dataset = "dataset"
prefix = "./data"
[[analyzers]]
	ngram = 1
	method = "ngram-word"
	[[analyzers.filter]]
		type = "icu-tokenizer"
	[[analyzers.filter]]
		type = "lowercase"
